[package]
name = "comet"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.2"
color-rs = "0.7.1"
glam = { version = "0.23.0", features = ["mint"] }
mint = "0.5.9"
rustc-hash = "1.1.0"
stardust-xr-molecules = "0.23.0"
stardust-xr-fusion = "0.38.1"
tokio = { version = "1.22.0", default-features = false, features = ["rt"] }
tween = { version = "2.0.0", features = ["glam"] }
map-range = "0.1.1"
